### ISSUE TITLE
I cant get it to install onto my Phone

### ISSUE THREAD

**Issue by Code-Tap** [ReactNativeCodility/GeoLocation#1]
Bundler is running
![screenshot from 2018-08-27 19-22-18](https://user-images.githubusercontent.com/23399537/44677755-a5b32a00-aa2e-11e8-8363-6b6c1d558aa3.png)

ADB Daemon is running
![screenshot from 2018-08-27 19-24-21](https://user-images.githubusercontent.com/23399537/44677855-e7dc6b80-aa2e-11e8-83cd-198d38267d57.png)

Followed your installation instructions with yarn
But instead of building to the device.. i get a mystery non-error message

![screenshot from 2018-08-27 19-26-34](https://user-images.githubusercontent.com/23399537/44678018-4275c780-aa2f-11e8-869b-b6258769961c.png)

Any advice for a noob?

**Comment by Govindz** [comment]
Hi,
Try using below link steps for connecting adb devices.
[https://facebook.github.io/react-native/docs/running-on-device](url)
and restart after completing the process. And also let me know if it helped you to solve the problem.
